name: "Release Workflow"

on:
  pull_request:
    types:
      - review_requested
    branches:
      - main

env:
  IMAGE_NAME: user/app
  DOCKERFILE: ./.config/Dockerfile
  OPW_VAULT: user/app

jobs:
  file_existence:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.dockerfile.outputs.files_exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Check for Dockerfile 
        id: dockerfile
        uses: andstor/file-existence-action@v3
        with:
          files: "${{ env.DOCKERFILE }}"

  semver:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.version.outputs.version }} 
      previous: ${{ steps.version.outputs.previous-version }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0

  docker:
    runs-on: ubuntu-latest
    if: ${{needs.file_existence.outputs.dockerfile}} == 'true'
    steps:
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKERHUB_USERNAME: op://${{ env.OPW_VAULT }}/docker/username
          DOCKERHUB_TOKEN: op://${{ env.OPW_VAULT }}/docker/api_token

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Validate build configuration
        uses: docker/build-push-action@v6.15.0
        with:
          call: check

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v6.15.0
        with:
          load: true
          tags: ${{ needs.semver.outputs.current }}
          file: ${{ env.DOCKERFILE }} 

      - name: Test
        run: |
          docker run --rm ${{ needs.semver.outputs.current }}

      - name: Build and push
        uses: docker/build-push-action@v6.15.0
        with:
          provenance: mode=max
          file: ${{ env.DOCKERFILE }}
          sbom: true
          platforms: linux/amd64,linux/arm64
          push: true
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            user/app:latest
            user/app:${{ needs.semver.outputs.current }}
            ghcr.io/user/app:latest
            ghcr.io/user/app:${{ needs.semver.outputs.current }}

  release:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Release.txt
            LICENSE

